### ISSUE TITLE
Better API for specifying variable names

### ISSUE THREAD

**Issue by MOZGIII** [vtavernier/efiboot-rs#14]
I feel like using strings (`String` and `&str`) as it's required now is a bit unsafe way to specify the EFI variable name. In EFI, to refer to a variable, we have to specify the `GUID` and the `Name` of the variable. Currently, it seems the interface is tailored to match the `efivar`/`efivarfs` implementation. I think it's a bad choice for the long term API design, and we should address it.

I propose introducing a stricter and a more structured type, something like this:

```rust
pub type GUID = [u8; 16];

#[derive(Debug, Clone)]
pub struct EFIVarName {
    guid: GUID,
    name: String,
}

impl EFIVarName {
    fn new(guid: GUID, name: String) -> EFIVarName {
        EFIVarName {
                guid: guid,
                name: name,
        }
    }
}

// Other impls...
```

This is just one way on how existing API could be improved, other option would be to explicitly pass the GUID and the name as separate arguments to the calls. However, it's not as flexible as the having a dedicated type.

If you like the idea of a dedicated type, I'd like to iterate on a `EFIVarName` type a bit to figure the best approach to implementing it.

**Comment by vtavernier** [comment]
I agree, the everything-in-a-`String` approach was only a first prototype. For the GUID type we might use the Uuid type provided by the [uuid crate](https://crates.io/crates/uuid), so we don't have to reimplement parsing and conversion to strings for backends that require it.

**Comment by MOZGIII** [comment]
It uses the same `[u8; 16]`, and it has some traits impls for converting From and Into `[u8; 16]`.
That said, I'd say it's a good idea to rely on `uuid` for conversions.
I'd still provide a type alias though (`GUID`).
