### ISSUE TITLE
Variables that have Parameters that exceed 1024 bytes fail to read successfully in Windows

### ISSUE THREAD

**Issue by mawelsh** [vtavernier/efiboot-rs#15]
Currently, the Windows SystemManager leverages a fixed 1024 byte (u8) buffer for reading EFI variables.  There are variables in systems such as Microsofts Project MU DFCI that will exceed this buffer and cause a failure to read.  A larger buffer (we have a codebase that uses 10240 bytes) or someway of reading the variable size and allocating dynamically should be used if it is desired to keep the buffer in the efivars crate.  Alternatively the buffer/size could be a parameter of VarManager.read(...).

**Comment by vtavernier** [comment]
Apparently there's no way to fetch the size of a variable using GetFirmwareEnvironmentVariableExW, so I think it's better for now to instead let the caller to `.read(...)` allocate a buffer which is large enough. The API has been updated to reflect that.
